# Generated by Django 3.0.8 on 2020-07-16 08:24

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_topmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='animehome',
            name='menu',
            field=wagtail.core.fields.StreamField([('items', wagtail.core.blocks.ListBlock(home.blocks.MenuItem))], blank=True, null=True),
        ),
    ]
