# Generated by Django 3.0.8 on 2020-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeepisode',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
