# Generated by Django 3.0.8 on 2020-07-14 01:49

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animepost',
            name='genres',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='genres', to='posts.Genre'),
        ),
    ]
