# Generated by Django 3.0.8 on 2020-07-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animepost',
            old_name='anime_tag',
            new_name='mediatag',
        ),
    ]
