# Generated by Django 3.0.8 on 2020-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200713_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='animepost',
            name='excerpt',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
