# Generated by Django 3.0.8 on 2020-07-25 22:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200724_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeepisode',
            name='order',
        ),
        migrations.AddField(
            model_name='animeepisode',
            name='links',
            field=wagtail.core.fields.StreamField([('media_link', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('media_type', wagtail.core.blocks.ChoiceBlock(choices=[('Mega', 'Mega'), ('gdrive', 'Google Drive'), ('telegram', 'Telegram')])), ('link', wagtail.core.blocks.CharBlock(max_length=200, required=True))])))], blank=True, null=True),
        ),
    ]
