# Generated by Django 3.0.8 on 2020-07-18 14:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_animeepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='content',
            field=wagtail.core.fields.StreamField([('richtextblock', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
