# Generated by Django 3.0.8 on 2020-07-25 22:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200725_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeepisode',
            name='links',
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('server', models.CharField(choices=[('MG', 'Mega'), ('DP', 'Dropbox'), ('GD', 'Google Drive'), ('TG', 'Telegram')], default='GD', max_length=2)),
                ('link', models.CharField(max_length=80, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='posts.BasePost')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
