# Generated by Django 3.0.8 on 2020-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200725_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialink',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
