# Generated by Django 3.0.8 on 2020-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_medialink_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialink',
            name='codec',
            field=models.CharField(choices=[('X265', 'x265'), ('X264', 'x264')], default='X264', max_length=5),
        ),
        migrations.AddField(
            model_name='medialink',
            name='resolution',
            field=models.CharField(choices=[('480', '480p'), ('720', '720p'), ('1080', '1080p'), ('Another', 'Otro...')], default='1080', max_length=10),
        ),
        migrations.AddField(
            model_name='medialink',
            name='subs',
            field=models.CharField(choices=[('SOFT', 'Softsubs'), ('HARD', 'Hardsubs')], default='HARD', max_length=10),
        ),
    ]
